server:
  port: 8001
  servlet:
    context-path: /register

spring:
  application:
    name: LIXF-Register
  boot:
    admin:
      client:
        url: http://${lixf-monitor-admin}:8401
        username: lixf
        password: 123456

  security:
    user:
      name: lixf
      password: 123456

eureka:
  instance:
    hostname: ${lixf-register}
  client:
    register-with-eureka: false
    fetch-registry: false
    instance-info-replication-interval-seconds: 30
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}${server.servlet.context-path}/eureka/

info:
  app:
    name: ${spring.application.name}
    description: "@project.description@"
    version: "@project.version@"

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS