FROM openjdk:8u212-jre
MAINTAINER Lixf 1183895890@qq.com

COPY lixf-auth-0.0.1-SNAPSHOT.jar /lixf/lixf-auth-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-Xmx256m", "-jar", "/lixf/lixf-auth-0.0.1-SNAPSHOT.jar"]

