server:
  port: 8401

spring:
  application:
    name: LIXF-Monitor-Admin
  boot:
    admin:
      ui:
        title: ${spring.application.name}
  security:
    user:
      name: lixf
      password: 123456